name: Hello World

on:
  push:
    branches:
      - main   # or your default branch
  workflow_dispatch: 

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, world!"
